; PlatformIO Project Configuration File for CLASSCAN ESP32 Firmware
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Include directories
build_flags = 
    -I include

; Required libraries
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.4
    madhephaestus/ESP32Servo @ ^3.0.5
